### PR TITLE
Added support for vmnet values to vnet_cli.

### PR DESCRIPTION
**Pull request by jameskyle**
- Adds configuration values to the vnet_cli vmnet lookup.
- No longer assumes dhcp is enabled on a net, leases set to None if dhcp
  disabled.
- Converts 'yes' and 'no' to True and False respectively.

Example::

    >>> net = vmfusion.vnet_cli("vnet6")
    Traceback (most recent call last):
    File "<ipython-input-41-26cf6871e9c5>", line 1, in <module>
        net = vmfusion.vnet_cli("vnet6")
    File "vmfusion/__init__.py", line 292, in __init__
        self._parse_networking()
    File "vmfusion/__init__.py", line 305, in _parse_networking
        raise ValueError(msg.format(self.name))
    ValueError: No network named vnet6 is defined!

    >>> net = vmfusion.vnet_cli("vmnet2")
    >>> net.dhcp
    False
    >>> net.netmask
    '255.255.255.0'
    >>> net.subnet
    '192.168.100.0'
    >>> net.nat
    True
    >>> net.virtual_adapter
    True

### CODE REVIEW

**Comment by msteinhoff** [comment]
Oh a PR, cool! :)

When the dhcpd stuff is optional, I suggest to move this in a private function next to parse_networking and to call parse_networking first so that the intention is more clear.

Also thanks for cleaning up the whitespace mess. It would be even more awesome if you can put that in a separate commit.

**Comment by jameskyle** [comment]
I'll try to get to the updates tomorrow or over the weekend.

**Comment by msteinhoff** [comment]
Hey, any news about the updates?

**Comment by jameskyle** [comment]
@msteinhoff canceling this pull, resubmitting two pulls. One for whitespace and one for features plus feedback changes.

**Pull request closed without merging**
